[package]
name = "mercury_land"
version = "2.7.0"
authors = ["logicfan", "champsing"]
edition = "2021"

[dependencies]
# web server
actix-web = "4.9"
actix-files = "0.6"
# serialization
serde = { version = "*", features = ["derive"] }
serde_json = "1.0"
# cryptography
rand = "0.8"
rsa = "0.9"
sha2 = "0.10"
hmac = "0.12"
jwt = "0.16"
# utility
derive_more = { version = "1.0", features = ["display", "from"] }
