name: Build Docker Image
on:
    push:
        tags:
            - '*'

jobs:
    build:
        name: Build Docker Image
        runs-on: ubuntu-latest
        steps:
            - name: Check out Source Code
              uses: actions/checkout@v4
            - name: Build Docker Image
              run: | 
                docker build -t mercury .
                docker images
                docker save --output mercury.tar mercury
            - name: Purge Artifacts
              uses: kolpav/purge-artifacts-action@v1
              with:
                token: ${{ secrets.GIT_PAT }}
                expire-in: 7days # Setting this to 0 will delete all artifacts
            - name: Upload Artifacts
              uses: actions/upload-artifact@v4
              with:
                name: mercury.tar
                path: ./mercury.tar

