name: Check
on:
  push:
    branches:
      - main
jobs:
  frontend:
    name: Frontend Check
    runs-on: ubuntu-latest
    steps:
      - name: Install Node.js
        uses: actions/setup-node@v4
      - name: Check out Source Code
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
          npm install -g vue-tsc vite 
          npm install
      - name: Build
        run: npm run build
  backend:
    name: Backend Check
    runs-on: ubuntu-latest
    steps:
      - name: Check out Source Code
        uses: actions/checkout@v4
      - name: Build Docker Image
        run: docker build -t mercury .
