name: Pull Request Check
on:
  pull_request: 
    types: [opened, synchronize, labeled]
    branches: [prod-web, prod-back]
jobs:
  vue_js:
    name: Test Vue.js
    if: ${{ github.event.label.name == 'front' }}
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
      - name: Check out Source Code
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
          npm install -g vue-tsc vite 
          npm install
      - name: Build
        run: npm run build
  rust:
    name: Test Rust Test
    if: ${{ github.event.label.name == 'back' }}
    runs-on: ubuntu-latest
    steps:
      - name: Setup Rust Toolchain
        run: rustup toolchain add nightly
      - name: Check out Source Code
        uses: actions/checkout@v4
      - name: Test
        run: cargo test
      - name: Build
        run: cargo build --release
  docker:
    name: Test Docker
    if: ${{ github.event.label.name == 'back' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out Source Code
        uses: actions/checkout@v4
      - name: Build
        run: docker build -t mercury .
