name: Merge to prod
on:
  pull_request: 
    types: [labeled]
    branches: [prod]

jobs:
  merge:
    name: Merge Pull Request
    if: ${{ github.event.label.name == 'merge' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo Hello