name: Merge to prod
on:
  issue_comment: 
    types: [created]

jobs:
  merge:
    name: Merge Pull Request
    if: ${{ github.event.issue.pull_request && github.event.comment.body == '/merge' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo Hello