name: Push-To-Github.io
on:
    push:
        branches:
            - main
jobs:
    push:
        name: Push To github.io
        runs-on: ubuntu-latest
        steps:
            - name: Install Node.js
              uses: actions/setup-node@v4
            - name: Check out Source Code
              uses: actions/checkout@v4
            - name: Install Dependencies
              run: |
                npm install -g vue-tsc vite 
                npm install
            - name: Build
              run: npm run build
            - name: Publish
              run: |
                cd dist
                ls -lR
                git init -b main
                git config user.name "Champsing's Best Friend"
                git config user.email "champsing_s_best_friend@example.com"
                git remote add origin https://champsing:${{ secrets.GIT_PAT }}@github.com/champsing/champsing.github.io
                git fetch origin
                git add -A
                git reset --soft origin/main
                git commit -m "sync from git workflow"
                git push origin main
                cd ..
